package com.mycompany.practica5;

import java.awt.Graphics;

/**
 *
 * @author Ayoze, Nicolás
 */
public class Main extends javax.swing.JFrame {
    
    Lienzo l = new Lienzo();
    Graphics g = l.getGraphics();        
    boolean c_red = true, c_green = true, c_blue = true;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //UtilsPractica5.seleccionarComponentes(bi, c_red, c_green, c_blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCorners = new javax.swing.ButtonGroup();
        lienzo1 = new com.mycompany.practica5.Lienzo();
        jPanelChooseColors = new javax.swing.JPanel();
        jLabelColors = new javax.swing.JLabel();
        jLabelColors1 = new javax.swing.JLabel();
        jCheckBoxALL = new javax.swing.JCheckBox();
        jCheckBoxRED = new javax.swing.JCheckBox();
        jCheckBoxGREEN = new javax.swing.JCheckBox();
        jCheckBoxBLUE = new javax.swing.JCheckBox();
        jPanelChooseLogoCorner = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelLogo1 = new javax.swing.JLabel();
        jRadioButtonUPLEFT = new javax.swing.JRadioButton();
        jRadioButtonDOWNLEFT = new javax.swing.JRadioButton();
        jRadioButtonDOWNRIGHT = new javax.swing.JRadioButton();
        jRadioButtonUPRIGHT = new javax.swing.JRadioButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lienzo1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanelChooseColors.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanelChooseColors.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelColors.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelColors.setText("RGB COLORS SELECTION");
        jPanelChooseColors.add(jLabelColors, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabelColors1.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        jLabelColors1.setText("SELECCIONA LOS COLORES QUE QUIERE MOSTRAR EN LA IMAGEN");
        jPanelChooseColors.add(jLabelColors1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jCheckBoxALL.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBoxALL.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jCheckBoxALL.setSelected(true);
        jCheckBoxALL.setText("ALL");
        jCheckBoxALL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxALLStateChanged(evt);
            }
        });
        jCheckBoxALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxALLActionPerformed(evt);
            }
        });
        jPanelChooseColors.add(jCheckBoxALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jCheckBoxRED.setBackground(new java.awt.Color(255, 153, 153));
        jCheckBoxRED.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jCheckBoxRED.setForeground(new java.awt.Color(255, 0, 0));
        jCheckBoxRED.setSelected(true);
        jCheckBoxRED.setText("RED");
        jCheckBoxRED.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxREDStateChanged(evt);
            }
        });
        jPanelChooseColors.add(jCheckBoxRED, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jCheckBoxGREEN.setBackground(new java.awt.Color(153, 255, 153));
        jCheckBoxGREEN.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jCheckBoxGREEN.setForeground(new java.awt.Color(0, 255, 0));
        jCheckBoxGREEN.setSelected(true);
        jCheckBoxGREEN.setText("GREEN");
        jCheckBoxGREEN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxGREENStateChanged(evt);
            }
        });
        jPanelChooseColors.add(jCheckBoxGREEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jCheckBoxBLUE.setBackground(new java.awt.Color(153, 153, 255));
        jCheckBoxBLUE.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jCheckBoxBLUE.setForeground(new java.awt.Color(0, 0, 255));
        jCheckBoxBLUE.setSelected(true);
        jCheckBoxBLUE.setText("BLUE");
        jCheckBoxBLUE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxBLUEStateChanged(evt);
            }
        });
        jPanelChooseColors.add(jCheckBoxBLUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jPanelChooseLogoCorner.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanelChooseLogoCorner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelLogo.setText("LOGO CORNER DISPLAY");
        jPanelChooseLogoCorner.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabelLogo1.setFont(new java.awt.Font("Tahoma", 1, 7)); // NOI18N
        jLabelLogo1.setText("SELECCIONA LA ESQUINA EN LA QUE QUIERE MOSTRAR EL LOGO");
        jPanelChooseLogoCorner.add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        buttonGroupCorners.add(jRadioButtonUPLEFT);
        jRadioButtonUPLEFT.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButtonUPLEFT.setSelected(true);
        jRadioButtonUPLEFT.setText("UP - LEFT");
        jRadioButtonUPLEFT.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 1, 1, new java.awt.Color(0, 0, 0)));
        jRadioButtonUPLEFT.setBorderPainted(true);
        jRadioButtonUPLEFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUPLEFTActionPerformed(evt);
            }
        });
        jPanelChooseLogoCorner.add(jRadioButtonUPLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        buttonGroupCorners.add(jRadioButtonDOWNLEFT);
        jRadioButtonDOWNLEFT.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButtonDOWNLEFT.setText("DOWN - LEFT");
        jRadioButtonDOWNLEFT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 2, 1, new java.awt.Color(0, 0, 0)));
        jRadioButtonDOWNLEFT.setBorderPainted(true);
        jRadioButtonDOWNLEFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDOWNLEFTActionPerformed(evt);
            }
        });
        jPanelChooseLogoCorner.add(jRadioButtonDOWNLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        buttonGroupCorners.add(jRadioButtonDOWNRIGHT);
        jRadioButtonDOWNRIGHT.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButtonDOWNRIGHT.setText("DOWN - RIGHT");
        jRadioButtonDOWNRIGHT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 2, new java.awt.Color(0, 0, 0)));
        jRadioButtonDOWNRIGHT.setBorderPainted(true);
        jRadioButtonDOWNRIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDOWNRIGHTActionPerformed(evt);
            }
        });
        jPanelChooseLogoCorner.add(jRadioButtonDOWNRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        buttonGroupCorners.add(jRadioButtonUPRIGHT);
        jRadioButtonUPRIGHT.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jRadioButtonUPRIGHT.setText("UP - RIGHT");
        jRadioButtonUPRIGHT.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        jRadioButtonUPRIGHT.setBorderPainted(true);
        jRadioButtonUPRIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUPRIGHTActionPerformed(evt);
            }
        });
        jPanelChooseLogoCorner.add(jRadioButtonUPRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelChooseColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButtonExit)
                .addGap(104, 104, 104)
                .addComponent(jPanelChooseLogoCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanelChooseLogoCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelChooseColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonExit))
                .addGap(18, 18, 18)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxALLActionPerformed

    private void jCheckBoxALLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxALLStateChanged
        if (jCheckBoxALL.isSelected() == true) {
            jCheckBoxBLUE.setSelected(true);
            jCheckBoxGREEN.setSelected(true);
            jCheckBoxRED.setSelected(true);
            c_red = true;
            c_green = true;
            c_blue = true;
            l.changeColor(c_red, c_green, c_blue);
        } else {
            if (jCheckBoxRED.isSelected() == true && jCheckBoxGREEN.isSelected() == true && jCheckBoxBLUE.isSelected() == true) {
                jCheckBoxALL.setSelected(true);
            }
        }
    }//GEN-LAST:event_jCheckBoxALLStateChanged

    private void jCheckBoxREDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxREDStateChanged
        if (jCheckBoxRED.isSelected() == false) {
            jCheckBoxALL.setSelected(false);
            
            c_red = false;
        } else {
            c_red = true;
            
            if (jCheckBoxGREEN.isSelected() == true && jCheckBoxBLUE.isSelected() == true) {
                jCheckBoxALL.setSelected(true);
            }
        }
        l.changeColor(c_red, c_green, c_blue);
    }//GEN-LAST:event_jCheckBoxREDStateChanged

    private void jCheckBoxGREENStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxGREENStateChanged
        if (jCheckBoxGREEN.isSelected() == false) {
            jCheckBoxALL.setSelected(false);
            
            c_green = false;
        } else {
            c_green = true;
            
            if (jCheckBoxRED.isSelected() == true && jCheckBoxBLUE.isSelected() == true) {
                jCheckBoxALL.setSelected(true);
            }
        }
        l.changeColor(c_red, c_green, c_blue);
    }//GEN-LAST:event_jCheckBoxGREENStateChanged

    private void jCheckBoxBLUEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxBLUEStateChanged
        if (jCheckBoxBLUE.isSelected() == false) {
            jCheckBoxALL.setSelected(false);
            
            c_blue = false;
        } else {
            c_blue = true;
            
            if (jCheckBoxRED.isSelected() == true && jCheckBoxGREEN.isSelected() == true) {
                jCheckBoxALL.setSelected(true);
            }
        }
        l.changeColor(c_red, c_green, c_blue);
    }//GEN-LAST:event_jCheckBoxBLUEStateChanged

    private void jRadioButtonDOWNLEFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDOWNLEFTActionPerformed
        if (jRadioButtonDOWNLEFT.isSelected() == true) {
            l.drawLogo(0, 750);
        }
    }//GEN-LAST:event_jRadioButtonDOWNLEFTActionPerformed

    private void jRadioButtonUPRIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUPRIGHTActionPerformed
        if (jRadioButtonUPRIGHT.isSelected() == true) {
            l.drawLogo(550, 0);
        }
    }//GEN-LAST:event_jRadioButtonUPRIGHTActionPerformed

    private void jRadioButtonUPLEFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUPLEFTActionPerformed
        if (jRadioButtonUPLEFT.isSelected() == true) {
            l.drawLogo(0, 0);
        }
    }//GEN-LAST:event_jRadioButtonUPLEFTActionPerformed

    private void jRadioButtonDOWNRIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDOWNRIGHTActionPerformed
        if (jRadioButtonDOWNRIGHT.isSelected() == true) {
            l.drawLogo(550, 750);
        }
    }//GEN-LAST:event_jRadioButtonDOWNRIGHTActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCorners;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JCheckBox jCheckBoxALL;
    private javax.swing.JCheckBox jCheckBoxBLUE;
    private javax.swing.JCheckBox jCheckBoxGREEN;
    private javax.swing.JCheckBox jCheckBoxRED;
    private javax.swing.JLabel jLabelColors;
    private javax.swing.JLabel jLabelColors1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JPanel jPanelChooseColors;
    private javax.swing.JPanel jPanelChooseLogoCorner;
    private javax.swing.JRadioButton jRadioButtonDOWNLEFT;
    private javax.swing.JRadioButton jRadioButtonDOWNRIGHT;
    private javax.swing.JRadioButton jRadioButtonUPLEFT;
    private javax.swing.JRadioButton jRadioButtonUPRIGHT;
    private com.mycompany.practica5.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
